# -*- coding: utf-8 -*-
#BJJ_CPN - Modelo de Red de Petri Coloreada (CPN) para técnicas de Brazilian Jiu-Jitsu

from snakes.nets import *
from snakes.plugins import load
load(['gv'], 'snakes.nets', 'nets')

def add_arc_safely(net, place, transition, label, direction):
    """Añade arcos evitando duplicados o conflictos de restricción."""
    try:
        if direction == "in":
            net.add_input(place, transition, label)
        elif direction == "out":
            net.add_output(place, transition, label)
    except ConstraintError:
        pass  # Ignorar duplicados


net = PetriNet('BJJ_CPN')
Luchador = ['A', 'O']

# PLACES --------------------------------------------------------------------
net.add_place(Place("Ashi_Garami_Inferior"))
net.add_place(Place("Ashi_Garami_Superior"))
net.add_place(Place("Atacando_Armbar"))
net.add_place(Place("Control_Lateral_Inferior"))
net.add_place(Place("Control_Lateral_Superior"))
net.add_place(Place("Control_Tortuga"))
net.add_place(Place("De_Pie"))
net.add_place(Place("Espalda_Control"))
net.add_place(Place("Espalda_Controlado"))
net.add_place(Place("Guardia_Abierta_Inferior"))
net.add_place(Place("Guardia_Abierta_Superior"))
net.add_place(Place("Guardia_Aplanada_Inferior"))
net.add_place(Place("Guardia_Aplanada_Superior"))
net.add_place(Place("Guardia_Cerrada_Inferior"))
net.add_place(Place("Guardia_Cerrada_Superior"))
net.add_place(Place("Guardia_DLR_Inferior"))
net.add_place(Place("Guardia_DLR_Superior"))
net.add_place(Place("Guardia_Mariposa_Inferior"))
net.add_place(Place("Guardia_Mariposa_Superior"))
net.add_place(Place("Guardia_de_Tortuga"))
net.add_place(Place("Media_Guardia_Inferior"))
net.add_place(Place("Media_Guardia_Profunda_Inferior"))
net.add_place(Place("Media_Guardia_Profunda_Superior"))
net.add_place(Place("Media_Guardia_Superior"))
net.add_place(Place("Montada_Inferior"))
net.add_place(Place("Montada_Superior"))
net.add_place(Place("Norte_Sur_Inferior"))
net.add_place(Place("Norte_Sur_Superior"))
net.add_place(Place("Rodilla_Abdomen_Inferior"))
net.add_place(Place("Rodilla_Abdomen_Superior"))
net.add_place(Place("S-Mount_Inferior"))
net.add_place(Place("S-Mount_Superior"))
net.add_place(Place("Siendo_Atacado_Armbar"))

# TRANSITIONS (Simétricas A/O) ----------------------------------------------
net.add_transition(Transition("T01_Derribo_de_Doble_Pierna_exitoso"))
add_arc_safely(net, "De_Pie", "T01_Derribo_de_Doble_Pierna_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T01_Derribo_de_Doble_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T01_Derribo_de_Doble_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T01_Derribo_de_Doble_Pierna_fallido"))
add_arc_safely(net, "De_Pie", "T01_Derribo_de_Doble_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T01_Derribo_de_Doble_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T01_inv_Derribo_de_Doble_Pierna_exitoso"))
add_arc_safely(net, "De_Pie", "T01_inv_Derribo_de_Doble_Pierna_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T01_inv_Derribo_de_Doble_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T01_inv_Derribo_de_Doble_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T01_inv_Derribo_de_Doble_Pierna_fallido"))
add_arc_safely(net, "De_Pie", "T01_inv_Derribo_de_Doble_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T01_inv_Derribo_de_Doble_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T02_Proyección_Osoto_Gari_exitoso"))
add_arc_safely(net, "De_Pie", "T02_Proyección_Osoto_Gari_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T02_Proyección_Osoto_Gari_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T02_Proyección_Osoto_Gari_exitoso", Value("O"), "out")

net.add_transition(Transition("T02_Proyección_Osoto_Gari_fallido"))
add_arc_safely(net, "De_Pie", "T02_Proyección_Osoto_Gari_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T02_Proyección_Osoto_Gari_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T02_inv_Proyección_Osoto_Gari_exitoso"))
add_arc_safely(net, "De_Pie", "T02_inv_Proyección_Osoto_Gari_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T02_inv_Proyección_Osoto_Gari_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T02_inv_Proyección_Osoto_Gari_exitoso", Value("O"), "out")

net.add_transition(Transition("T02_inv_Proyección_Osoto_Gari_fallido"))
add_arc_safely(net, "De_Pie", "T02_inv_Proyección_Osoto_Gari_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T02_inv_Proyección_Osoto_Gari_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T03_Pase_de_Guardia_Torreando_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_Pase_de_Guardia_Torreando_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_Pase_de_Guardia_Torreando_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T03_Pase_de_Guardia_Torreando_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T03_Pase_de_Guardia_Torreando_exitoso", Value("O"), "out")

net.add_transition(Transition("T03_Pase_de_Guardia_Torreando_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_Pase_de_Guardia_Torreando_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_Pase_de_Guardia_Torreando_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_Pase_de_Guardia_Torreando_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_Pase_de_Guardia_Torreando_fallido", Value("O"), "out")

net.add_transition(Transition("T03_inv_Pase_de_Guardia_Torreando_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_inv_Pase_de_Guardia_Torreando_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_inv_Pase_de_Guardia_Torreando_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T03_inv_Pase_de_Guardia_Torreando_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T03_inv_Pase_de_Guardia_Torreando_exitoso", Value("O"), "out")

net.add_transition(Transition("T03_inv_Pase_de_Guardia_Torreando_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_inv_Pase_de_Guardia_Torreando_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_inv_Pase_de_Guardia_Torreando_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T03_inv_Pase_de_Guardia_Torreando_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T03_inv_Pase_de_Guardia_Torreando_fallido", Value("O"), "out")

net.add_transition(Transition("T04_Pase_de_Rodilla_Deslizante_exitoso"))
add_arc_safely(net, "Media_Guardia_Superior", "T04_Pase_de_Rodilla_Deslizante_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T04_Pase_de_Rodilla_Deslizante_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T04_Pase_de_Rodilla_Deslizante_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T04_Pase_de_Rodilla_Deslizante_exitoso", Value("O"), "out")

net.add_transition(Transition("T04_Pase_de_Rodilla_Deslizante_fallido"))
add_arc_safely(net, "Media_Guardia_Superior", "T04_Pase_de_Rodilla_Deslizante_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T04_Pase_de_Rodilla_Deslizante_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T04_Pase_de_Rodilla_Deslizante_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T04_Pase_de_Rodilla_Deslizante_fallido", Value("O"), "out")

net.add_transition(Transition("T04_inv_Pase_de_Rodilla_Deslizante_exitoso"))
add_arc_safely(net, "Media_Guardia_Inferior", "T04_inv_Pase_de_Rodilla_Deslizante_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T04_inv_Pase_de_Rodilla_Deslizante_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T04_inv_Pase_de_Rodilla_Deslizante_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T04_inv_Pase_de_Rodilla_Deslizante_exitoso", Value("O"), "out")

net.add_transition(Transition("T04_inv_Pase_de_Rodilla_Deslizante_fallido"))
add_arc_safely(net, "Media_Guardia_Inferior", "T04_inv_Pase_de_Rodilla_Deslizante_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T04_inv_Pase_de_Rodilla_Deslizante_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T04_inv_Pase_de_Rodilla_Deslizante_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T04_inv_Pase_de_Rodilla_Deslizante_fallido", Value("O"), "out")

net.add_transition(Transition("T05_Pase_de_Guardia_por_Apilamiento_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T05_Pase_de_Guardia_por_Apilamiento_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T05_Pase_de_Guardia_por_Apilamiento_exitoso", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T05_Pase_de_Guardia_por_Apilamiento_exitoso", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Inferior", "T05_Pase_de_Guardia_por_Apilamiento_exitoso", Value("O"), "out")

net.add_transition(Transition("T05_Pase_de_Guardia_por_Apilamiento_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T05_Pase_de_Guardia_por_Apilamiento_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T05_Pase_de_Guardia_por_Apilamiento_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T05_Pase_de_Guardia_por_Apilamiento_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T05_Pase_de_Guardia_por_Apilamiento_fallido", Value("O"), "out")

net.add_transition(Transition("T05_inv_Pase_de_Guardia_por_Apilamiento_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T05_inv_Pase_de_Guardia_por_Apilamiento_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T05_inv_Pase_de_Guardia_por_Apilamiento_exitoso", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T05_inv_Pase_de_Guardia_por_Apilamiento_exitoso", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Superior", "T05_inv_Pase_de_Guardia_por_Apilamiento_exitoso", Value("O"), "out")

net.add_transition(Transition("T05_inv_Pase_de_Guardia_por_Apilamiento_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T05_inv_Pase_de_Guardia_por_Apilamiento_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T05_inv_Pase_de_Guardia_por_Apilamiento_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T05_inv_Pase_de_Guardia_por_Apilamiento_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T05_inv_Pase_de_Guardia_por_Apilamiento_fallido", Value("O"), "out")

net.add_transition(Transition("T06_Estrangulamiento_de_Triángulo_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T06_Estrangulamiento_de_Triángulo_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T06_Estrangulamiento_de_Triángulo_exitoso", Value("O"), "in")

net.add_transition(Transition("T06_Estrangulamiento_de_Triángulo_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T06_Estrangulamiento_de_Triángulo_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T06_Estrangulamiento_de_Triángulo_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T06_Estrangulamiento_de_Triángulo_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T06_Estrangulamiento_de_Triángulo_fallido", Value("O"), "out")

net.add_transition(Transition("T06_inv_Estrangulamiento_de_Triángulo_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T06_inv_Estrangulamiento_de_Triángulo_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T06_inv_Estrangulamiento_de_Triángulo_exitoso", Value("O"), "in")

net.add_transition(Transition("T06_inv_Estrangulamiento_de_Triángulo_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T06_inv_Estrangulamiento_de_Triángulo_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T06_inv_Estrangulamiento_de_Triángulo_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T06_inv_Estrangulamiento_de_Triángulo_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T06_inv_Estrangulamiento_de_Triángulo_fallido", Value("O"), "out")

net.add_transition(Transition("T07_Palanca_de_Brazo_(Armbar)_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T07_Palanca_de_Brazo_(Armbar)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T07_Palanca_de_Brazo_(Armbar)_exitoso", Value("O"), "in")

net.add_transition(Transition("T07_Palanca_de_Brazo_(Armbar)_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T07_Palanca_de_Brazo_(Armbar)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T07_Palanca_de_Brazo_(Armbar)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T07_Palanca_de_Brazo_(Armbar)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T07_Palanca_de_Brazo_(Armbar)_fallido", Value("O"), "out")

net.add_transition(Transition("T07_inv_Palanca_de_Brazo_(Armbar)_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T07_inv_Palanca_de_Brazo_(Armbar)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T07_inv_Palanca_de_Brazo_(Armbar)_exitoso", Value("O"), "in")

net.add_transition(Transition("T07_inv_Palanca_de_Brazo_(Armbar)_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T07_inv_Palanca_de_Brazo_(Armbar)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T07_inv_Palanca_de_Brazo_(Armbar)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T07_inv_Palanca_de_Brazo_(Armbar)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T07_inv_Palanca_de_Brazo_(Armbar)_fallido", Value("O"), "out")

net.add_transition(Transition("T08_Estrangulamiento_de_Guillotina_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T08_Estrangulamiento_de_Guillotina_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T08_Estrangulamiento_de_Guillotina_exitoso", Value("O"), "in")

net.add_transition(Transition("T08_Estrangulamiento_de_Guillotina_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T08_Estrangulamiento_de_Guillotina_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T08_Estrangulamiento_de_Guillotina_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T08_Estrangulamiento_de_Guillotina_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T08_Estrangulamiento_de_Guillotina_fallido", Value("O"), "out")

net.add_transition(Transition("T08_inv_Estrangulamiento_de_Guillotina_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T08_inv_Estrangulamiento_de_Guillotina_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T08_inv_Estrangulamiento_de_Guillotina_exitoso", Value("O"), "in")

net.add_transition(Transition("T08_inv_Estrangulamiento_de_Guillotina_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T08_inv_Estrangulamiento_de_Guillotina_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T08_inv_Estrangulamiento_de_Guillotina_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T08_inv_Estrangulamiento_de_Guillotina_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T08_inv_Estrangulamiento_de_Guillotina_fallido", Value("O"), "out")

net.add_transition(Transition("T09_Raspado_de_Tijera_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T09_Raspado_de_Tijera_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T09_Raspado_de_Tijera_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T09_Raspado_de_Tijera_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T09_Raspado_de_Tijera_exitoso", Value("O"), "out")

net.add_transition(Transition("T09_Raspado_de_Tijera_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T09_Raspado_de_Tijera_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T09_Raspado_de_Tijera_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T09_Raspado_de_Tijera_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T09_Raspado_de_Tijera_fallido", Value("O"), "out")

net.add_transition(Transition("T09_inv_Raspado_de_Tijera_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T09_inv_Raspado_de_Tijera_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T09_inv_Raspado_de_Tijera_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T09_inv_Raspado_de_Tijera_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T09_inv_Raspado_de_Tijera_exitoso", Value("O"), "out")

net.add_transition(Transition("T09_inv_Raspado_de_Tijera_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T09_inv_Raspado_de_Tijera_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T09_inv_Raspado_de_Tijera_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T09_inv_Raspado_de_Tijera_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T09_inv_Raspado_de_Tijera_fallido", Value("O"), "out")

net.add_transition(Transition("T10_Omoplata_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_Omoplata_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_Omoplata_exitoso", Value("O"), "in")

net.add_transition(Transition("T10_Omoplata_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_Omoplata_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_Omoplata_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_Omoplata_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_Omoplata_fallido", Value("O"), "out")

net.add_transition(Transition("T10_inv_Omoplata_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_inv_Omoplata_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_inv_Omoplata_exitoso", Value("O"), "in")

net.add_transition(Transition("T10_inv_Omoplata_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_inv_Omoplata_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_inv_Omoplata_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T10_inv_Omoplata_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T10_inv_Omoplata_fallido", Value("O"), "out")

net.add_transition(Transition("T11_Americana_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Superior", "T11_Americana_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T11_Americana_desde_Montada_exitoso", Value("O"), "in")

net.add_transition(Transition("T11_Americana_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Superior", "T11_Americana_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T11_Americana_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T11_Americana_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T11_Americana_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T11_inv_Americana_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T11_inv_Americana_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T11_inv_Americana_desde_Montada_exitoso", Value("O"), "in")

net.add_transition(Transition("T11_inv_Americana_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Inferior", "T11_inv_Americana_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T11_inv_Americana_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T11_inv_Americana_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T11_inv_Americana_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T12_Estrangulamiento_Cruzado_exitoso"))
add_arc_safely(net, "Montada_Superior", "T12_Estrangulamiento_Cruzado_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T12_Estrangulamiento_Cruzado_exitoso", Value("O"), "in")

net.add_transition(Transition("T12_Estrangulamiento_Cruzado_fallido"))
add_arc_safely(net, "Montada_Superior", "T12_Estrangulamiento_Cruzado_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T12_Estrangulamiento_Cruzado_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T12_Estrangulamiento_Cruzado_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T12_Estrangulamiento_Cruzado_fallido", Value("O"), "out")

net.add_transition(Transition("T12_inv_Estrangulamiento_Cruzado_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T12_inv_Estrangulamiento_Cruzado_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T12_inv_Estrangulamiento_Cruzado_exitoso", Value("O"), "in")

net.add_transition(Transition("T12_inv_Estrangulamiento_Cruzado_fallido"))
add_arc_safely(net, "Montada_Inferior", "T12_inv_Estrangulamiento_Cruzado_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T12_inv_Estrangulamiento_Cruzado_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T12_inv_Estrangulamiento_Cruzado_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T12_inv_Estrangulamiento_Cruzado_fallido", Value("O"), "out")

net.add_transition(Transition("T13_Palanca_de_Brazo_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Superior", "T13_Palanca_de_Brazo_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T13_Palanca_de_Brazo_desde_Montada_exitoso", Value("O"), "in")

net.add_transition(Transition("T13_Palanca_de_Brazo_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Superior", "T13_Palanca_de_Brazo_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T13_Palanca_de_Brazo_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T13_Palanca_de_Brazo_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T13_Palanca_de_Brazo_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T13_inv_Palanca_de_Brazo_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T13_inv_Palanca_de_Brazo_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T13_inv_Palanca_de_Brazo_desde_Montada_exitoso", Value("O"), "in")

net.add_transition(Transition("T13_inv_Palanca_de_Brazo_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Inferior", "T13_inv_Palanca_de_Brazo_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T13_inv_Palanca_de_Brazo_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T13_inv_Palanca_de_Brazo_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T13_inv_Palanca_de_Brazo_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T14_Kimura_desde_Control_Lateral_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T14_Kimura_desde_Control_Lateral_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T14_Kimura_desde_Control_Lateral_exitoso", Value("O"), "in")

net.add_transition(Transition("T14_Kimura_desde_Control_Lateral_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T14_Kimura_desde_Control_Lateral_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T14_Kimura_desde_Control_Lateral_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T14_Kimura_desde_Control_Lateral_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T14_Kimura_desde_Control_Lateral_fallido", Value("O"), "out")

net.add_transition(Transition("T14_inv_Kimura_desde_Control_Lateral_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T14_inv_Kimura_desde_Control_Lateral_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T14_inv_Kimura_desde_Control_Lateral_exitoso", Value("O"), "in")

net.add_transition(Transition("T14_inv_Kimura_desde_Control_Lateral_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T14_inv_Kimura_desde_Control_Lateral_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T14_inv_Kimura_desde_Control_Lateral_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T14_inv_Kimura_desde_Control_Lateral_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T14_inv_Kimura_desde_Control_Lateral_fallido", Value("O"), "out")

net.add_transition(Transition("T15_Estrangulamiento_D'Arce_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T15_Estrangulamiento_D'Arce_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T15_Estrangulamiento_D'Arce_exitoso", Value("O"), "in")

net.add_transition(Transition("T15_Estrangulamiento_D'Arce_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T15_Estrangulamiento_D'Arce_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T15_Estrangulamiento_D'Arce_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T15_Estrangulamiento_D'Arce_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T15_Estrangulamiento_D'Arce_fallido", Value("O"), "out")

net.add_transition(Transition("T15_inv_Estrangulamiento_D'Arce_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T15_inv_Estrangulamiento_D'Arce_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T15_inv_Estrangulamiento_D'Arce_exitoso", Value("O"), "in")

net.add_transition(Transition("T15_inv_Estrangulamiento_D'Arce_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T15_inv_Estrangulamiento_D'Arce_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T15_inv_Estrangulamiento_D'Arce_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T15_inv_Estrangulamiento_D'Arce_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T15_inv_Estrangulamiento_D'Arce_fallido", Value("O"), "out")

net.add_transition(Transition("T16_Mata_León_(Rear_Naked_Choke)_exitoso"))
add_arc_safely(net, "Espalda_Control", "T16_Mata_León_(Rear_Naked_Choke)_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T16_Mata_León_(Rear_Naked_Choke)_exitoso", Value("O"), "in")

net.add_transition(Transition("T16_Mata_León_(Rear_Naked_Choke)_fallido"))
add_arc_safely(net, "Espalda_Control", "T16_Mata_León_(Rear_Naked_Choke)_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T16_Mata_León_(Rear_Naked_Choke)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T16_Mata_León_(Rear_Naked_Choke)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T16_Mata_León_(Rear_Naked_Choke)_fallido", Value("O"), "out")

net.add_transition(Transition("T16_inv_Mata_León_(Rear_Naked_Choke)_exitoso"))
add_arc_safely(net, "Espalda_Controlado", "T16_inv_Mata_León_(Rear_Naked_Choke)_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T16_inv_Mata_León_(Rear_Naked_Choke)_exitoso", Value("O"), "in")

net.add_transition(Transition("T16_inv_Mata_León_(Rear_Naked_Choke)_fallido"))
add_arc_safely(net, "Espalda_Controlado", "T16_inv_Mata_León_(Rear_Naked_Choke)_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T16_inv_Mata_León_(Rear_Naked_Choke)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T16_inv_Mata_León_(Rear_Naked_Choke)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T16_inv_Mata_León_(Rear_Naked_Choke)_fallido", Value("O"), "out")

net.add_transition(Transition("T17_Escape_de_Upa_(Puente_y_Giro)_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T17_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T17_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T17_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T17_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("O"), "out")

net.add_transition(Transition("T17_Escape_de_Upa_(Puente_y_Giro)_fallido"))
add_arc_safely(net, "Montada_Inferior", "T17_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T17_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T17_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T17_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("O"), "out")

net.add_transition(Transition("T17_inv_Escape_de_Upa_(Puente_y_Giro)_exitoso"))
add_arc_safely(net, "Montada_Superior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_exitoso", Value("O"), "out")

net.add_transition(Transition("T17_inv_Escape_de_Upa_(Puente_y_Giro)_fallido"))
add_arc_safely(net, "Montada_Superior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T17_inv_Escape_de_Upa_(Puente_y_Giro)_fallido", Value("O"), "out")

net.add_transition(Transition("T18_Fuga_de_Cadera_(Shrimping)_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T18_Fuga_de_Cadera_(Shrimping)_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T18_Fuga_de_Cadera_(Shrimping)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T18_Fuga_de_Cadera_(Shrimping)_exitoso", Value("O"), "out")

net.add_transition(Transition("T18_Fuga_de_Cadera_(Shrimping)_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T18_Fuga_de_Cadera_(Shrimping)_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T18_Fuga_de_Cadera_(Shrimping)_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T18_Fuga_de_Cadera_(Shrimping)_fallido", Value("O"), "out")

net.add_transition(Transition("T18_inv_Fuga_de_Cadera_(Shrimping)_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T18_inv_Fuga_de_Cadera_(Shrimping)_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T18_inv_Fuga_de_Cadera_(Shrimping)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T18_inv_Fuga_de_Cadera_(Shrimping)_exitoso", Value("O"), "out")

net.add_transition(Transition("T18_inv_Fuga_de_Cadera_(Shrimping)_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T18_inv_Fuga_de_Cadera_(Shrimping)_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T18_inv_Fuga_de_Cadera_(Shrimping)_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T18_inv_Fuga_de_Cadera_(Shrimping)_fallido", Value("O"), "out")

net.add_transition(Transition("T19_Recuperación_de_Guardia_(Reguard)_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T19_Recuperación_de_Guardia_(Reguard)_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T19_Recuperación_de_Guardia_(Reguard)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T19_Recuperación_de_Guardia_(Reguard)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T19_Recuperación_de_Guardia_(Reguard)_exitoso", Value("O"), "out")

net.add_transition(Transition("T19_Recuperación_de_Guardia_(Reguard)_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T19_Recuperación_de_Guardia_(Reguard)_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T19_Recuperación_de_Guardia_(Reguard)_fallido", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T19_Recuperación_de_Guardia_(Reguard)_fallido", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Superior", "T19_Recuperación_de_Guardia_(Reguard)_fallido", Value("O"), "out")

net.add_transition(Transition("T19_inv_Recuperación_de_Guardia_(Reguard)_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T19_inv_Recuperación_de_Guardia_(Reguard)_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T19_inv_Recuperación_de_Guardia_(Reguard)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T19_inv_Recuperación_de_Guardia_(Reguard)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T19_inv_Recuperación_de_Guardia_(Reguard)_exitoso", Value("O"), "out")

net.add_transition(Transition("T19_inv_Recuperación_de_Guardia_(Reguard)_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T19_inv_Recuperación_de_Guardia_(Reguard)_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T19_inv_Recuperación_de_Guardia_(Reguard)_fallido", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T19_inv_Recuperación_de_Guardia_(Reguard)_fallido", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Inferior", "T19_inv_Recuperación_de_Guardia_(Reguard)_fallido", Value("O"), "out")

net.add_transition(Transition("T20_Escape_de_la_Espalda_exitoso"))
add_arc_safely(net, "Espalda_Controlado", "T20_Escape_de_la_Espalda_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T20_Escape_de_la_Espalda_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T20_Escape_de_la_Espalda_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Tortuga", "T20_Escape_de_la_Espalda_exitoso", Value("O"), "out")

net.add_transition(Transition("T20_Escape_de_la_Espalda_fallido"))
add_arc_safely(net, "Espalda_Controlado", "T20_Escape_de_la_Espalda_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T20_Escape_de_la_Espalda_fallido", Value("O"), "in")
add_arc_safely(net, "Espalda_Controlado", "T20_Escape_de_la_Espalda_fallido", Value("A"), "out")
add_arc_safely(net, "Espalda_Control", "T20_Escape_de_la_Espalda_fallido", Value("O"), "out")

net.add_transition(Transition("T20_inv_Escape_de_la_Espalda_exitoso"))
add_arc_safely(net, "Espalda_Control", "T20_inv_Escape_de_la_Espalda_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T20_inv_Escape_de_la_Espalda_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Tortuga", "T20_inv_Escape_de_la_Espalda_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_de_Tortuga", "T20_inv_Escape_de_la_Espalda_exitoso", Value("O"), "out")

net.add_transition(Transition("T20_inv_Escape_de_la_Espalda_fallido"))
add_arc_safely(net, "Espalda_Control", "T20_inv_Escape_de_la_Espalda_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T20_inv_Escape_de_la_Espalda_fallido", Value("O"), "in")
add_arc_safely(net, "Espalda_Control", "T20_inv_Escape_de_la_Espalda_fallido", Value("A"), "out")
add_arc_safely(net, "Espalda_Controlado", "T20_inv_Escape_de_la_Espalda_fallido", Value("O"), "out")

net.add_transition(Transition("T21_Transición_a_Rodilla_al_Abdomen_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T21_Transición_a_Rodilla_al_Abdomen_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T21_Transición_a_Rodilla_al_Abdomen_exitoso", Value("O"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T21_Transición_a_Rodilla_al_Abdomen_exitoso", Value("A"), "out")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T21_Transición_a_Rodilla_al_Abdomen_exitoso", Value("O"), "out")

net.add_transition(Transition("T21_Transición_a_Rodilla_al_Abdomen_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T21_Transición_a_Rodilla_al_Abdomen_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T21_Transición_a_Rodilla_al_Abdomen_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T21_Transición_a_Rodilla_al_Abdomen_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T21_Transición_a_Rodilla_al_Abdomen_fallido", Value("O"), "out")

net.add_transition(Transition("T21_inv_Transición_a_Rodilla_al_Abdomen_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T21_inv_Transición_a_Rodilla_al_Abdomen_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T21_inv_Transición_a_Rodilla_al_Abdomen_exitoso", Value("O"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T21_inv_Transición_a_Rodilla_al_Abdomen_exitoso", Value("A"), "out")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T21_inv_Transición_a_Rodilla_al_Abdomen_exitoso", Value("O"), "out")

net.add_transition(Transition("T21_inv_Transición_a_Rodilla_al_Abdomen_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T21_inv_Transición_a_Rodilla_al_Abdomen_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T21_inv_Transición_a_Rodilla_al_Abdomen_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T21_inv_Transición_a_Rodilla_al_Abdomen_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T21_inv_Transición_a_Rodilla_al_Abdomen_fallido", Value("O"), "out")

net.add_transition(Transition("T22_Transición_a_la_Montada_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T22_Transición_a_la_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T22_Transición_a_la_Montada_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T22_Transición_a_la_Montada_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T22_Transición_a_la_Montada_exitoso", Value("O"), "out")

net.add_transition(Transition("T22_Transición_a_la_Montada_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T22_Transición_a_la_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T22_Transición_a_la_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T22_Transición_a_la_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T22_Transición_a_la_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T22_inv_Transición_a_la_Montada_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T22_inv_Transición_a_la_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T22_inv_Transición_a_la_Montada_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T22_inv_Transición_a_la_Montada_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T22_inv_Transición_a_la_Montada_exitoso", Value("O"), "out")

net.add_transition(Transition("T22_inv_Transición_a_la_Montada_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T22_inv_Transición_a_la_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T22_inv_Transición_a_la_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T22_inv_Transición_a_la_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T22_inv_Transición_a_la_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T23_Toma_de_Espalda_desde_Tortuga_exitoso"))
add_arc_safely(net, "Control_Tortuga", "T23_Toma_de_Espalda_desde_Tortuga_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T23_Toma_de_Espalda_desde_Tortuga_exitoso", Value("O"), "in")
add_arc_safely(net, "Espalda_Control", "T23_Toma_de_Espalda_desde_Tortuga_exitoso", Value("A"), "out")
add_arc_safely(net, "Espalda_Controlado", "T23_Toma_de_Espalda_desde_Tortuga_exitoso", Value("O"), "out")

net.add_transition(Transition("T23_Toma_de_Espalda_desde_Tortuga_fallido"))
add_arc_safely(net, "Control_Tortuga", "T23_Toma_de_Espalda_desde_Tortuga_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T23_Toma_de_Espalda_desde_Tortuga_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T23_Toma_de_Espalda_desde_Tortuga_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T23_Toma_de_Espalda_desde_Tortuga_fallido", Value("O"), "out")

net.add_transition(Transition("T23_inv_Toma_de_Espalda_desde_Tortuga_exitoso"))
add_arc_safely(net, "Guardia_de_Tortuga", "T23_inv_Toma_de_Espalda_desde_Tortuga_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T23_inv_Toma_de_Espalda_desde_Tortuga_exitoso", Value("O"), "in")
add_arc_safely(net, "Espalda_Controlado", "T23_inv_Toma_de_Espalda_desde_Tortuga_exitoso", Value("A"), "out")
add_arc_safely(net, "Espalda_Control", "T23_inv_Toma_de_Espalda_desde_Tortuga_exitoso", Value("O"), "out")

net.add_transition(Transition("T23_inv_Toma_de_Espalda_desde_Tortuga_fallido"))
add_arc_safely(net, "Guardia_de_Tortuga", "T23_inv_Toma_de_Espalda_desde_Tortuga_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T23_inv_Toma_de_Espalda_desde_Tortuga_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T23_inv_Toma_de_Espalda_desde_Tortuga_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T23_inv_Toma_de_Espalda_desde_Tortuga_fallido", Value("O"), "out")

net.add_transition(Transition("T24_Romper_Postura_en_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_Romper_Postura_en_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_Romper_Postura_en_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_Romper_Postura_en_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_Romper_Postura_en_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T24_Romper_Postura_en_Guardia_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_Romper_Postura_en_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_Romper_Postura_en_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_Romper_Postura_en_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_Romper_Postura_en_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T24_inv_Romper_Postura_en_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_inv_Romper_Postura_en_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_inv_Romper_Postura_en_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_inv_Romper_Postura_en_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_inv_Romper_Postura_en_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T24_inv_Romper_Postura_en_Guardia_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_inv_Romper_Postura_en_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_inv_Romper_Postura_en_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T24_inv_Romper_Postura_en_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T24_inv_Romper_Postura_en_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T25_Ponerse_de_Pie_en_la_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T25_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T25_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T25_Ponerse_de_Pie_en_la_Guardia_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_Ponerse_de_Pie_en_la_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_Ponerse_de_Pie_en_la_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_Ponerse_de_Pie_en_la_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_Ponerse_de_Pie_en_la_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T25_inv_Ponerse_de_Pie_en_la_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T25_inv_Ponerse_de_Pie_en_la_Guardia_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T25_inv_Ponerse_de_Pie_en_la_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T26_Raspado_de_Gancho_(Butterfly)_exitoso"))
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T26_Raspado_de_Gancho_(Butterfly)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T26_Raspado_de_Gancho_(Butterfly)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T26_Raspado_de_Gancho_(Butterfly)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T26_Raspado_de_Gancho_(Butterfly)_exitoso", Value("O"), "out")

net.add_transition(Transition("T26_Raspado_de_Gancho_(Butterfly)_fallido"))
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T26_Raspado_de_Gancho_(Butterfly)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T26_Raspado_de_Gancho_(Butterfly)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Aplanada_Inferior", "T26_Raspado_de_Gancho_(Butterfly)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Aplanada_Superior", "T26_Raspado_de_Gancho_(Butterfly)_fallido", Value("O"), "out")

net.add_transition(Transition("T26_inv_Raspado_de_Gancho_(Butterfly)_exitoso"))
add_arc_safely(net, "Guardia_Mariposa_Superior", "T26_inv_Raspado_de_Gancho_(Butterfly)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T26_inv_Raspado_de_Gancho_(Butterfly)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T26_inv_Raspado_de_Gancho_(Butterfly)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T26_inv_Raspado_de_Gancho_(Butterfly)_exitoso", Value("O"), "out")

net.add_transition(Transition("T26_inv_Raspado_de_Gancho_(Butterfly)_fallido"))
add_arc_safely(net, "Guardia_Mariposa_Superior", "T26_inv_Raspado_de_Gancho_(Butterfly)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T26_inv_Raspado_de_Gancho_(Butterfly)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Aplanada_Superior", "T26_inv_Raspado_de_Gancho_(Butterfly)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Aplanada_Inferior", "T26_inv_Raspado_de_Gancho_(Butterfly)_fallido", Value("O"), "out")

net.add_transition(Transition("T27_Raspado_de_De_La_Riva_exitoso"))
add_arc_safely(net, "Guardia_DLR_Inferior", "T27_Raspado_de_De_La_Riva_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Superior", "T27_Raspado_de_De_La_Riva_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T27_Raspado_de_De_La_Riva_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T27_Raspado_de_De_La_Riva_exitoso", Value("O"), "out")

net.add_transition(Transition("T27_Raspado_de_De_La_Riva_fallido"))
add_arc_safely(net, "Guardia_DLR_Inferior", "T27_Raspado_de_De_La_Riva_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Superior", "T27_Raspado_de_De_La_Riva_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T27_Raspado_de_De_La_Riva_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T27_Raspado_de_De_La_Riva_fallido", Value("O"), "out")

net.add_transition(Transition("T27_inv_Raspado_de_De_La_Riva_exitoso"))
add_arc_safely(net, "Guardia_DLR_Superior", "T27_inv_Raspado_de_De_La_Riva_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Inferior", "T27_inv_Raspado_de_De_La_Riva_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T27_inv_Raspado_de_De_La_Riva_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T27_inv_Raspado_de_De_La_Riva_exitoso", Value("O"), "out")

net.add_transition(Transition("T27_inv_Raspado_de_De_La_Riva_fallido"))
add_arc_safely(net, "Guardia_DLR_Superior", "T27_inv_Raspado_de_De_La_Riva_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Inferior", "T27_inv_Raspado_de_De_La_Riva_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T27_inv_Raspado_de_De_La_Riva_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T27_inv_Raspado_de_De_La_Riva_fallido", Value("O"), "out")

net.add_transition(Transition("T28_Llave_de_Talón_(Heel_Hook)_exitoso"))
add_arc_safely(net, "Ashi_Garami_Inferior", "T28_Llave_de_Talón_(Heel_Hook)_exitoso", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Superior", "T28_Llave_de_Talón_(Heel_Hook)_exitoso", Value("O"), "in")

net.add_transition(Transition("T28_Llave_de_Talón_(Heel_Hook)_fallido"))
add_arc_safely(net, "Ashi_Garami_Inferior", "T28_Llave_de_Talón_(Heel_Hook)_fallido", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Superior", "T28_Llave_de_Talón_(Heel_Hook)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T28_Llave_de_Talón_(Heel_Hook)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T28_Llave_de_Talón_(Heel_Hook)_fallido", Value("O"), "out")

net.add_transition(Transition("T28_inv_Llave_de_Talón_(Heel_Hook)_exitoso"))
add_arc_safely(net, "Ashi_Garami_Superior", "T28_inv_Llave_de_Talón_(Heel_Hook)_exitoso", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Inferior", "T28_inv_Llave_de_Talón_(Heel_Hook)_exitoso", Value("O"), "in")

net.add_transition(Transition("T28_inv_Llave_de_Talón_(Heel_Hook)_fallido"))
add_arc_safely(net, "Ashi_Garami_Superior", "T28_inv_Llave_de_Talón_(Heel_Hook)_fallido", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Inferior", "T28_inv_Llave_de_Talón_(Heel_Hook)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T28_inv_Llave_de_Talón_(Heel_Hook)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T28_inv_Llave_de_Talón_(Heel_Hook)_fallido", Value("O"), "out")

net.add_transition(Transition("T29_Pasaje_de_Doble_Esgrima_exitoso"))
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_Pasaje_de_Doble_Esgrima_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_Pasaje_de_Doble_Esgrima_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T29_Pasaje_de_Doble_Esgrima_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T29_Pasaje_de_Doble_Esgrima_exitoso", Value("O"), "out")

net.add_transition(Transition("T29_Pasaje_de_Doble_Esgrima_fallido"))
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_Pasaje_de_Doble_Esgrima_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_Pasaje_de_Doble_Esgrima_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_Pasaje_de_Doble_Esgrima_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_Pasaje_de_Doble_Esgrima_fallido", Value("O"), "out")

net.add_transition(Transition("T29_inv_Pasaje_de_Doble_Esgrima_exitoso"))
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_inv_Pasaje_de_Doble_Esgrima_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_inv_Pasaje_de_Doble_Esgrima_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T29_inv_Pasaje_de_Doble_Esgrima_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T29_inv_Pasaje_de_Doble_Esgrima_exitoso", Value("O"), "out")

net.add_transition(Transition("T29_inv_Pasaje_de_Doble_Esgrima_fallido"))
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_inv_Pasaje_de_Doble_Esgrima_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_inv_Pasaje_de_Doble_Esgrima_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T29_inv_Pasaje_de_Doble_Esgrima_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T29_inv_Pasaje_de_Doble_Esgrima_fallido", Value("O"), "out")

net.add_transition(Transition("T30_Estrangulamiento_de_Arco_y_Flecha_exitoso"))
add_arc_safely(net, "Espalda_Control", "T30_Estrangulamiento_de_Arco_y_Flecha_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T30_Estrangulamiento_de_Arco_y_Flecha_exitoso", Value("O"), "in")

net.add_transition(Transition("T30_Estrangulamiento_de_Arco_y_Flecha_fallido"))
add_arc_safely(net, "Espalda_Control", "T30_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Controlado", "T30_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T30_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T30_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("O"), "out")

net.add_transition(Transition("T30_inv_Estrangulamiento_de_Arco_y_Flecha_exitoso"))
add_arc_safely(net, "Espalda_Controlado", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_exitoso", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_exitoso", Value("O"), "in")

net.add_transition(Transition("T30_inv_Estrangulamiento_de_Arco_y_Flecha_fallido"))
add_arc_safely(net, "Espalda_Controlado", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("A"), "in")
add_arc_safely(net, "Espalda_Control", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T30_inv_Estrangulamiento_de_Arco_y_Flecha_fallido", Value("O"), "out")

net.add_transition(Transition("T31_Llamada_a_la_Guardia_(Guard_Pull)_exitoso"))
add_arc_safely(net, "De_Pie", "T31_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T31_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T31_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", Value("O"), "out")

net.add_transition(Transition("T31_Llamada_a_la_Guardia_(Guard_Pull)_fallido"))
add_arc_safely(net, "De_Pie", "T31_Llamada_a_la_Guardia_(Guard_Pull)_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T31_Llamada_a_la_Guardia_(Guard_Pull)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T31_Llamada_a_la_Guardia_(Guard_Pull)_fallido", Value("O"), "out")

net.add_transition(Transition("T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_exitoso"))
add_arc_safely(net, "De_Pie", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_exitoso", Value("O"), "out")

net.add_transition(Transition("T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_fallido"))
add_arc_safely(net, "De_Pie", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T31_inv_Llamada_a_la_Guardia_(Guard_Pull)_fallido", Value("O"), "out")

net.add_transition(Transition("T32_Derribo_a_una_Pierna_exitoso"))
add_arc_safely(net, "De_Pie", "T32_Derribo_a_una_Pierna_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T32_Derribo_a_una_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T32_Derribo_a_una_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T32_Derribo_a_una_Pierna_fallido"))
add_arc_safely(net, "De_Pie", "T32_Derribo_a_una_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T32_Derribo_a_una_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T32_inv_Derribo_a_una_Pierna_exitoso"))
add_arc_safely(net, "De_Pie", "T32_inv_Derribo_a_una_Pierna_exitoso", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T32_inv_Derribo_a_una_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T32_inv_Derribo_a_una_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T32_inv_Derribo_a_una_Pierna_fallido"))
add_arc_safely(net, "De_Pie", "T32_inv_Derribo_a_una_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "in")
add_arc_safely(net, "De_Pie", "T32_inv_Derribo_a_una_Pierna_fallido", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T33_Pasaje_de_Arrastre_de_Pierna_exitoso"))
add_arc_safely(net, "Guardia_DLR_Superior", "T33_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Inferior", "T33_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T33_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T33_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T33_Pasaje_de_Arrastre_de_Pierna_fallido"))
add_arc_safely(net, "Guardia_DLR_Superior", "T33_Pasaje_de_Arrastre_de_Pierna_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Inferior", "T33_Pasaje_de_Arrastre_de_Pierna_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T33_Pasaje_de_Arrastre_de_Pierna_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T33_Pasaje_de_Arrastre_de_Pierna_fallido", Value("O"), "out")

net.add_transition(Transition("T33_inv_Pasaje_de_Arrastre_de_Pierna_exitoso"))
add_arc_safely(net, "Guardia_DLR_Inferior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Superior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_exitoso", Value("O"), "out")

net.add_transition(Transition("T33_inv_Pasaje_de_Arrastre_de_Pierna_fallido"))
add_arc_safely(net, "Guardia_DLR_Inferior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_DLR_Superior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T33_inv_Pasaje_de_Arrastre_de_Pierna_fallido", Value("O"), "out")

net.add_transition(Transition("T34_Raspado_de_Péndulo_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T34_Raspado_de_Péndulo_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T34_Raspado_de_Péndulo_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T34_Raspado_de_Péndulo_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T34_Raspado_de_Péndulo_exitoso", Value("O"), "out")

net.add_transition(Transition("T34_Raspado_de_Péndulo_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T34_Raspado_de_Péndulo_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T34_Raspado_de_Péndulo_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T34_Raspado_de_Péndulo_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T34_Raspado_de_Péndulo_fallido", Value("O"), "out")

net.add_transition(Transition("T34_inv_Raspado_de_Péndulo_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T34_inv_Raspado_de_Péndulo_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T34_inv_Raspado_de_Péndulo_exitoso", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T34_inv_Raspado_de_Péndulo_exitoso", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T34_inv_Raspado_de_Péndulo_exitoso", Value("O"), "out")

net.add_transition(Transition("T34_inv_Raspado_de_Péndulo_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T34_inv_Raspado_de_Péndulo_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T34_inv_Raspado_de_Péndulo_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T34_inv_Raspado_de_Péndulo_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T34_inv_Raspado_de_Péndulo_fallido", Value("O"), "out")

net.add_transition(Transition("T35_Inversión_desde_Media_Guardia_exitoso"))
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T35_Inversión_desde_Media_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Profunda_Superior", "T35_Inversión_desde_Media_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T35_Inversión_desde_Media_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T35_Inversión_desde_Media_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T35_Inversión_desde_Media_Guardia_fallido"))
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T35_Inversión_desde_Media_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Profunda_Superior", "T35_Inversión_desde_Media_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T35_Inversión_desde_Media_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T35_Inversión_desde_Media_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T35_inv_Inversión_desde_Media_Guardia_exitoso"))
add_arc_safely(net, "Media_Guardia_Profunda_Superior", "T35_inv_Inversión_desde_Media_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T35_inv_Inversión_desde_Media_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T35_inv_Inversión_desde_Media_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T35_inv_Inversión_desde_Media_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T35_inv_Inversión_desde_Media_Guardia_fallido"))
add_arc_safely(net, "Media_Guardia_Profunda_Superior", "T35_inv_Inversión_desde_Media_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T35_inv_Inversión_desde_Media_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T35_inv_Inversión_desde_Media_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T35_inv_Inversión_desde_Media_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T36_Defensa_de_Palanca_de_Brazo_exitoso"))
add_arc_safely(net, "Siendo_Atacado_Armbar", "T36_Defensa_de_Palanca_de_Brazo_exitoso", Value("A"), "in")
add_arc_safely(net, "Atacando_Armbar", "T36_Defensa_de_Palanca_de_Brazo_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T36_Defensa_de_Palanca_de_Brazo_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T36_Defensa_de_Palanca_de_Brazo_exitoso", Value("O"), "out")

net.add_transition(Transition("T36_Defensa_de_Palanca_de_Brazo_fallido"))
add_arc_safely(net, "Siendo_Atacado_Armbar", "T36_Defensa_de_Palanca_de_Brazo_fallido", Value("A"), "in")
add_arc_safely(net, "Atacando_Armbar", "T36_Defensa_de_Palanca_de_Brazo_fallido", Value("O"), "in")

net.add_transition(Transition("T36_inv_Defensa_de_Palanca_de_Brazo_exitoso"))
add_arc_safely(net, "Atacando_Armbar", "T36_inv_Defensa_de_Palanca_de_Brazo_exitoso", Value("A"), "in")
add_arc_safely(net, "Siendo_Atacado_Armbar", "T36_inv_Defensa_de_Palanca_de_Brazo_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T36_inv_Defensa_de_Palanca_de_Brazo_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T36_inv_Defensa_de_Palanca_de_Brazo_exitoso", Value("O"), "out")

net.add_transition(Transition("T36_inv_Defensa_de_Palanca_de_Brazo_fallido"))
add_arc_safely(net, "Atacando_Armbar", "T36_inv_Defensa_de_Palanca_de_Brazo_fallido", Value("A"), "in")
add_arc_safely(net, "Siendo_Atacado_Armbar", "T36_inv_Defensa_de_Palanca_de_Brazo_fallido", Value("O"), "in")

net.add_transition(Transition("T37_Escape_de_Rodilla_al_Abdomen_exitoso"))
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_Escape_de_Rodilla_al_Abdomen_exitoso", Value("A"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_Escape_de_Rodilla_al_Abdomen_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T37_Escape_de_Rodilla_al_Abdomen_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T37_Escape_de_Rodilla_al_Abdomen_exitoso", Value("O"), "out")

net.add_transition(Transition("T37_Escape_de_Rodilla_al_Abdomen_fallido"))
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_Escape_de_Rodilla_al_Abdomen_fallido", Value("A"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_Escape_de_Rodilla_al_Abdomen_fallido", Value("O"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_Escape_de_Rodilla_al_Abdomen_fallido", Value("A"), "out")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_Escape_de_Rodilla_al_Abdomen_fallido", Value("O"), "out")

net.add_transition(Transition("T37_inv_Escape_de_Rodilla_al_Abdomen_exitoso"))
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_inv_Escape_de_Rodilla_al_Abdomen_exitoso", Value("A"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_inv_Escape_de_Rodilla_al_Abdomen_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T37_inv_Escape_de_Rodilla_al_Abdomen_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T37_inv_Escape_de_Rodilla_al_Abdomen_exitoso", Value("O"), "out")

net.add_transition(Transition("T37_inv_Escape_de_Rodilla_al_Abdomen_fallido"))
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_inv_Escape_de_Rodilla_al_Abdomen_fallido", Value("A"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_inv_Escape_de_Rodilla_al_Abdomen_fallido", Value("O"), "in")
add_arc_safely(net, "Rodilla_Abdomen_Superior", "T37_inv_Escape_de_Rodilla_al_Abdomen_fallido", Value("A"), "out")
add_arc_safely(net, "Rodilla_Abdomen_Inferior", "T37_inv_Escape_de_Rodilla_al_Abdomen_fallido", Value("O"), "out")

net.add_transition(Transition("T38_Ponerse_de_Pie_desde_Tortuga_exitoso"))
add_arc_safely(net, "Guardia_de_Tortuga", "T38_Ponerse_de_Pie_desde_Tortuga_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T38_Ponerse_de_Pie_desde_Tortuga_exitoso", Value("O"), "in")
add_arc_safely(net, "De_Pie", "T38_Ponerse_de_Pie_desde_Tortuga_exitoso", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T38_Ponerse_de_Pie_desde_Tortuga_fallido"))
add_arc_safely(net, "Guardia_de_Tortuga", "T38_Ponerse_de_Pie_desde_Tortuga_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T38_Ponerse_de_Pie_desde_Tortuga_fallido", Value("O"), "in")
add_arc_safely(net, "Espalda_Controlado", "T38_Ponerse_de_Pie_desde_Tortuga_fallido", Value("A"), "out")
add_arc_safely(net, "Espalda_Control", "T38_Ponerse_de_Pie_desde_Tortuga_fallido", Value("O"), "out")

net.add_transition(Transition("T38_inv_Ponerse_de_Pie_desde_Tortuga_exitoso"))
add_arc_safely(net, "Control_Tortuga", "T38_inv_Ponerse_de_Pie_desde_Tortuga_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T38_inv_Ponerse_de_Pie_desde_Tortuga_exitoso", Value("O"), "in")
add_arc_safely(net, "De_Pie", "T38_inv_Ponerse_de_Pie_desde_Tortuga_exitoso", MultiArc([Value("A"), Value("O")]), "out")

net.add_transition(Transition("T38_inv_Ponerse_de_Pie_desde_Tortuga_fallido"))
add_arc_safely(net, "Control_Tortuga", "T38_inv_Ponerse_de_Pie_desde_Tortuga_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T38_inv_Ponerse_de_Pie_desde_Tortuga_fallido", Value("O"), "in")
add_arc_safely(net, "Espalda_Control", "T38_inv_Ponerse_de_Pie_desde_Tortuga_fallido", Value("A"), "out")
add_arc_safely(net, "Espalda_Controlado", "T38_inv_Ponerse_de_Pie_desde_Tortuga_fallido", Value("O"), "out")

net.add_transition(Transition("T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso"))
add_arc_safely(net, "Guardia_de_Tortuga", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("O"), "out")

net.add_transition(Transition("T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido"))
add_arc_safely(net, "Guardia_de_Tortuga", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Tortuga", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T39_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("O"), "out")

net.add_transition(Transition("T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso"))
add_arc_safely(net, "Control_Tortuga", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_exitoso", Value("O"), "out")

net.add_transition(Transition("T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido"))
add_arc_safely(net, "Control_Tortuga", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T39_inv_Rodar_hacia_la_Guardia_(desde_Tortuga)_fallido", Value("O"), "out")

net.add_transition(Transition("T40_Escape_de_Piernas_(Leg_Pummeling)_exitoso"))
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Superior", "T40_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T40_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T40_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("O"), "out")

net.add_transition(Transition("T40_Escape_de_Piernas_(Leg_Pummeling)_fallido"))
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Superior", "T40_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("O"), "in")
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("A"), "out")
add_arc_safely(net, "Ashi_Garami_Superior", "T40_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("O"), "out")

net.add_transition(Transition("T40_inv_Escape_de_Piernas_(Leg_Pummeling)_exitoso"))
add_arc_safely(net, "Ashi_Garami_Superior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_exitoso", Value("O"), "out")

net.add_transition(Transition("T40_inv_Escape_de_Piernas_(Leg_Pummeling)_fallido"))
add_arc_safely(net, "Ashi_Garami_Superior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("A"), "in")
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("O"), "in")
add_arc_safely(net, "Ashi_Garami_Superior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("A"), "out")
add_arc_safely(net, "Ashi_Garami_Inferior", "T40_inv_Escape_de_Piernas_(Leg_Pummeling)_fallido", Value("O"), "out")

net.add_transition(Transition("T41_Transición_a_Norte-Sur_exitoso"))
add_arc_safely(net, "Control_Lateral_Superior", "T41_Transición_a_Norte-Sur_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T41_Transición_a_Norte-Sur_exitoso", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T41_Transición_a_Norte-Sur_exitoso", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Inferior", "T41_Transición_a_Norte-Sur_exitoso", Value("O"), "out")

net.add_transition(Transition("T41_Transición_a_Norte-Sur_fallido"))
add_arc_safely(net, "Control_Lateral_Superior", "T41_Transición_a_Norte-Sur_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T41_Transición_a_Norte-Sur_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_de_Tortuga", "T41_Transición_a_Norte-Sur_fallido", Value("A"), "out")
add_arc_safely(net, "Control_Tortuga", "T41_Transición_a_Norte-Sur_fallido", Value("O"), "out")

net.add_transition(Transition("T41_inv_Transición_a_Norte-Sur_exitoso"))
add_arc_safely(net, "Control_Lateral_Inferior", "T41_inv_Transición_a_Norte-Sur_exitoso", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T41_inv_Transición_a_Norte-Sur_exitoso", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T41_inv_Transición_a_Norte-Sur_exitoso", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Superior", "T41_inv_Transición_a_Norte-Sur_exitoso", Value("O"), "out")

net.add_transition(Transition("T41_inv_Transición_a_Norte-Sur_fallido"))
add_arc_safely(net, "Control_Lateral_Inferior", "T41_inv_Transición_a_Norte-Sur_fallido", Value("A"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T41_inv_Transición_a_Norte-Sur_fallido", Value("O"), "in")
add_arc_safely(net, "Control_Tortuga", "T41_inv_Transición_a_Norte-Sur_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_de_Tortuga", "T41_inv_Transición_a_Norte-Sur_fallido", Value("O"), "out")

net.add_transition(Transition("T42_Transición_a_S-Mount_exitoso"))
add_arc_safely(net, "Montada_Superior", "T42_Transición_a_S-Mount_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T42_Transición_a_S-Mount_exitoso", Value("O"), "in")
add_arc_safely(net, "S-Mount_Superior", "T42_Transición_a_S-Mount_exitoso", Value("A"), "out")
add_arc_safely(net, "S-Mount_Inferior", "T42_Transición_a_S-Mount_exitoso", Value("O"), "out")

net.add_transition(Transition("T42_Transición_a_S-Mount_fallido"))
add_arc_safely(net, "Montada_Superior", "T42_Transición_a_S-Mount_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T42_Transición_a_S-Mount_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Superior", "T42_Transición_a_S-Mount_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Inferior", "T42_Transición_a_S-Mount_fallido", Value("O"), "out")

net.add_transition(Transition("T42_inv_Transición_a_S-Mount_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T42_inv_Transición_a_S-Mount_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T42_inv_Transición_a_S-Mount_exitoso", Value("O"), "in")
add_arc_safely(net, "S-Mount_Inferior", "T42_inv_Transición_a_S-Mount_exitoso", Value("A"), "out")
add_arc_safely(net, "S-Mount_Superior", "T42_inv_Transición_a_S-Mount_exitoso", Value("O"), "out")

net.add_transition(Transition("T42_inv_Transición_a_S-Mount_fallido"))
add_arc_safely(net, "Montada_Inferior", "T42_inv_Transición_a_S-Mount_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T42_inv_Transición_a_S-Mount_fallido", Value("O"), "in")
add_arc_safely(net, "Montada_Inferior", "T42_inv_Transición_a_S-Mount_fallido", Value("A"), "out")
add_arc_safely(net, "Montada_Superior", "T42_inv_Transición_a_S-Mount_fallido", Value("O"), "out")

net.add_transition(Transition("T43_Toma_de_Espalda_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Superior", "T43_Toma_de_Espalda_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T43_Toma_de_Espalda_desde_Montada_exitoso", Value("O"), "in")
add_arc_safely(net, "Espalda_Control", "T43_Toma_de_Espalda_desde_Montada_exitoso", Value("A"), "out")
add_arc_safely(net, "Espalda_Controlado", "T43_Toma_de_Espalda_desde_Montada_exitoso", Value("O"), "out")

net.add_transition(Transition("T43_Toma_de_Espalda_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Superior", "T43_Toma_de_Espalda_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Inferior", "T43_Toma_de_Espalda_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T43_Toma_de_Espalda_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T43_Toma_de_Espalda_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T43_inv_Toma_de_Espalda_desde_Montada_exitoso"))
add_arc_safely(net, "Montada_Inferior", "T43_inv_Toma_de_Espalda_desde_Montada_exitoso", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T43_inv_Toma_de_Espalda_desde_Montada_exitoso", Value("O"), "in")
add_arc_safely(net, "Espalda_Controlado", "T43_inv_Toma_de_Espalda_desde_Montada_exitoso", Value("A"), "out")
add_arc_safely(net, "Espalda_Control", "T43_inv_Toma_de_Espalda_desde_Montada_exitoso", Value("O"), "out")

net.add_transition(Transition("T43_inv_Toma_de_Espalda_desde_Montada_fallido"))
add_arc_safely(net, "Montada_Inferior", "T43_inv_Toma_de_Espalda_desde_Montada_fallido", Value("A"), "in")
add_arc_safely(net, "Montada_Superior", "T43_inv_Toma_de_Espalda_desde_Montada_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T43_inv_Toma_de_Espalda_desde_Montada_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T43_inv_Toma_de_Espalda_desde_Montada_fallido", Value("O"), "out")

net.add_transition(Transition("T44_Forzar_Media_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_Forzar_Media_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_Forzar_Media_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T44_Forzar_Media_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Inferior", "T44_Forzar_Media_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T44_Forzar_Media_Guardia_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_Forzar_Media_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_Forzar_Media_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_Forzar_Media_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_Forzar_Media_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T44_inv_Forzar_Media_Guardia_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_inv_Forzar_Media_Guardia_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_inv_Forzar_Media_Guardia_exitoso", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T44_inv_Forzar_Media_Guardia_exitoso", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T44_inv_Forzar_Media_Guardia_exitoso", Value("O"), "out")

net.add_transition(Transition("T44_inv_Forzar_Media_Guardia_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_inv_Forzar_Media_Guardia_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_inv_Forzar_Media_Guardia_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T44_inv_Forzar_Media_Guardia_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T44_inv_Forzar_Media_Guardia_fallido", Value("O"), "out")

net.add_transition(Transition("T45_Establecer_Guardia_De_La_Riva_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_Establecer_Guardia_De_La_Riva_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_Establecer_Guardia_De_La_Riva_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_DLR_Inferior", "T45_Establecer_Guardia_De_La_Riva_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_DLR_Superior", "T45_Establecer_Guardia_De_La_Riva_exitoso", Value("O"), "out")

net.add_transition(Transition("T45_Establecer_Guardia_De_La_Riva_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_Establecer_Guardia_De_La_Riva_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_Establecer_Guardia_De_La_Riva_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_Establecer_Guardia_De_La_Riva_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_Establecer_Guardia_De_La_Riva_fallido", Value("O"), "out")

net.add_transition(Transition("T45_inv_Establecer_Guardia_De_La_Riva_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_inv_Establecer_Guardia_De_La_Riva_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_inv_Establecer_Guardia_De_La_Riva_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_DLR_Superior", "T45_inv_Establecer_Guardia_De_La_Riva_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_DLR_Inferior", "T45_inv_Establecer_Guardia_De_La_Riva_exitoso", Value("O"), "out")

net.add_transition(Transition("T45_inv_Establecer_Guardia_De_La_Riva_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_inv_Establecer_Guardia_De_La_Riva_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_inv_Establecer_Guardia_De_La_Riva_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T45_inv_Establecer_Guardia_De_La_Riva_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T45_inv_Establecer_Guardia_De_La_Riva_fallido", Value("O"), "out")

net.add_transition(Transition("T46_Establecer_Guardia_de_Mariposa_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_Establecer_Guardia_de_Mariposa_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_Establecer_Guardia_de_Mariposa_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T46_Establecer_Guardia_de_Mariposa_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T46_Establecer_Guardia_de_Mariposa_exitoso", Value("O"), "out")

net.add_transition(Transition("T46_Establecer_Guardia_de_Mariposa_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_Establecer_Guardia_de_Mariposa_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_Establecer_Guardia_de_Mariposa_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_Establecer_Guardia_de_Mariposa_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_Establecer_Guardia_de_Mariposa_fallido", Value("O"), "out")

net.add_transition(Transition("T46_inv_Establecer_Guardia_de_Mariposa_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_inv_Establecer_Guardia_de_Mariposa_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_inv_Establecer_Guardia_de_Mariposa_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Mariposa_Superior", "T46_inv_Establecer_Guardia_de_Mariposa_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Mariposa_Inferior", "T46_inv_Establecer_Guardia_de_Mariposa_exitoso", Value("O"), "out")

net.add_transition(Transition("T46_inv_Establecer_Guardia_de_Mariposa_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_inv_Establecer_Guardia_de_Mariposa_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_inv_Establecer_Guardia_de_Mariposa_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T46_inv_Establecer_Guardia_de_Mariposa_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T46_inv_Establecer_Guardia_de_Mariposa_fallido", Value("O"), "out")

net.add_transition(Transition("T47_Estrangulamiento_Norte-Sur_exitoso"))
add_arc_safely(net, "Norte_Sur_Superior", "T47_Estrangulamiento_Norte-Sur_exitoso", Value("A"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T47_Estrangulamiento_Norte-Sur_exitoso", Value("O"), "in")

net.add_transition(Transition("T47_Estrangulamiento_Norte-Sur_fallido"))
add_arc_safely(net, "Norte_Sur_Superior", "T47_Estrangulamiento_Norte-Sur_fallido", Value("A"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T47_Estrangulamiento_Norte-Sur_fallido", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T47_Estrangulamiento_Norte-Sur_fallido", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Inferior", "T47_Estrangulamiento_Norte-Sur_fallido", Value("O"), "out")

net.add_transition(Transition("T47_inv_Estrangulamiento_Norte-Sur_exitoso"))
add_arc_safely(net, "Norte_Sur_Inferior", "T47_inv_Estrangulamiento_Norte-Sur_exitoso", Value("A"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T47_inv_Estrangulamiento_Norte-Sur_exitoso", Value("O"), "in")

net.add_transition(Transition("T47_inv_Estrangulamiento_Norte-Sur_fallido"))
add_arc_safely(net, "Norte_Sur_Inferior", "T47_inv_Estrangulamiento_Norte-Sur_fallido", Value("A"), "in")
add_arc_safely(net, "Norte_Sur_Superior", "T47_inv_Estrangulamiento_Norte-Sur_fallido", Value("O"), "in")
add_arc_safely(net, "Norte_Sur_Inferior", "T47_inv_Estrangulamiento_Norte-Sur_fallido", Value("A"), "out")
add_arc_safely(net, "Norte_Sur_Superior", "T47_inv_Estrangulamiento_Norte-Sur_fallido", Value("O"), "out")

net.add_transition(Transition("T48_Pasaje_por_Encima_(Over-Under)_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T48_Pasaje_por_Encima_(Over-Under)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T48_Pasaje_por_Encima_(Over-Under)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T48_Pasaje_por_Encima_(Over-Under)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T48_Pasaje_por_Encima_(Over-Under)_exitoso", Value("O"), "out")

net.add_transition(Transition("T48_Pasaje_por_Encima_(Over-Under)_fallido"))
add_arc_safely(net, "Guardia_Abierta_Superior", "T48_Pasaje_por_Encima_(Over-Under)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T48_Pasaje_por_Encima_(Over-Under)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T48_Pasaje_por_Encima_(Over-Under)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T48_Pasaje_por_Encima_(Over-Under)_fallido", Value("O"), "out")

net.add_transition(Transition("T48_inv_Pasaje_por_Encima_(Over-Under)_exitoso"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T48_inv_Pasaje_por_Encima_(Over-Under)_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T48_inv_Pasaje_por_Encima_(Over-Under)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T48_inv_Pasaje_por_Encima_(Over-Under)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T48_inv_Pasaje_por_Encima_(Over-Under)_exitoso", Value("O"), "out")

net.add_transition(Transition("T48_inv_Pasaje_por_Encima_(Over-Under)_fallido"))
add_arc_safely(net, "Guardia_Abierta_Inferior", "T48_inv_Pasaje_por_Encima_(Over-Under)_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T48_inv_Pasaje_por_Encima_(Over-Under)_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T48_inv_Pasaje_por_Encima_(Over-Under)_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T48_inv_Pasaje_por_Encima_(Over-Under)_fallido", Value("O"), "out")

net.add_transition(Transition("T49_Pasaje_de_Aplastamiento_(Smash)_exitoso"))
add_arc_safely(net, "Media_Guardia_Superior", "T49_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T49_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Superior", "T49_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Inferior", "T49_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("O"), "out")

net.add_transition(Transition("T49_Pasaje_de_Aplastamiento_(Smash)_fallido"))
add_arc_safely(net, "Media_Guardia_Superior", "T49_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Inferior", "T49_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T49_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T49_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("O"), "out")

net.add_transition(Transition("T49_inv_Pasaje_de_Aplastamiento_(Smash)_exitoso"))
add_arc_safely(net, "Media_Guardia_Inferior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("O"), "in")
add_arc_safely(net, "Control_Lateral_Inferior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("A"), "out")
add_arc_safely(net, "Control_Lateral_Superior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_exitoso", Value("O"), "out")

net.add_transition(Transition("T49_inv_Pasaje_de_Aplastamiento_(Smash)_fallido"))
add_arc_safely(net, "Media_Guardia_Inferior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("A"), "in")
add_arc_safely(net, "Media_Guardia_Superior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("O"), "in")
add_arc_safely(net, "Media_Guardia_Profunda_Inferior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("A"), "out")
add_arc_safely(net, "Media_Guardia_Superior", "T49_inv_Pasaje_de_Aplastamiento_(Smash)_fallido", Value("O"), "out")

net.add_transition(Transition("T50_Recomponer_Postura_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_Recomponer_Postura_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_Recomponer_Postura_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Superior", "T50_Recomponer_Postura_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T50_Recomponer_Postura_exitoso", Value("O"), "out")

net.add_transition(Transition("T50_Recomponer_Postura_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_Recomponer_Postura_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_Recomponer_Postura_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_Recomponer_Postura_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_Recomponer_Postura_fallido", Value("O"), "out")

net.add_transition(Transition("T50_inv_Recomponer_Postura_exitoso"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_inv_Recomponer_Postura_exitoso", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_inv_Recomponer_Postura_exitoso", Value("O"), "in")
add_arc_safely(net, "Guardia_Abierta_Inferior", "T50_inv_Recomponer_Postura_exitoso", Value("A"), "out")
add_arc_safely(net, "Guardia_Abierta_Superior", "T50_inv_Recomponer_Postura_exitoso", Value("O"), "out")

net.add_transition(Transition("T50_inv_Recomponer_Postura_fallido"))
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_inv_Recomponer_Postura_fallido", Value("A"), "in")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_inv_Recomponer_Postura_fallido", Value("O"), "in")
add_arc_safely(net, "Guardia_Cerrada_Inferior", "T50_inv_Recomponer_Postura_fallido", Value("A"), "out")
add_arc_safely(net, "Guardia_Cerrada_Superior", "T50_inv_Recomponer_Postura_fallido", Value("O"), "out")

# MARCADO INICIAL -----------------------------------------------------------
net.place("De_Pie").add("A")
net.place("De_Pie").add("O")

print("Modelo BJJ_CPN simétrico cargado correctamente.")
